name: 上传MLForLLC_Release.json

on:
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:

jobs:
  push-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Download JSON
        run: curl -o MLForLLC_Release.json https://api.github.com/repos/LocalizeLimbusCompany/MelonLoader-LLC/releases
          
      - name: Add JSON to repo
        run: |
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
          git add MLForLLC_Release.json
          git commit -m "Update Installer release."
          git push https://github-actions[bot]:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository_owner }}/LLC_jsontest
